image: python:latest
    
variables:
  NEW_COMMIT: git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA

before_script:
  - python -V # Print out python version for debugging
  #- pip install virtualenv
  #- virtualenv venv
  #- source venv/bin/activate

flake8:
  script:
  - pip install flake8
  - flake8 .
  allow_failure: true