image: python:latest
    
variables:
  NEW_COMMIT: git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA

before_script:
  - python -V # Print out python version for debugging
 # - pip install virtualenv
 # - virtualenv venv
 # - source venv/bin/activate

pyflakes:
  script:
  - pip install pyflakes
  - echo $($NEW_COMMIT) # What's new in the commit
  - pyflakes "$($NEW_COMMIT)"

PyFlakes (All Code):
  script:
  - pip install pyflakes
  - pyflakes .