image: python:latest

before_script:
  - python -V # Print out python version for debugging
  #- pip install virtualenv
  #- virtualenv venv
  #- source venv/bin/activate

flake8:
  script:
  - pip install flake8
  - flake8 .