image: python:latest

flake8:
  script:
  - python -V
  - pip install flake8
  - flake8 .

services:
  - postgres

variables:
  POSTGRES_DB: lightningbot
  POSTGRES_USER: lightningbot
  POSTGRES_PASSWORD: "test"

schema-test:
  image: postgres
  script:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "\i schema.sql"
