-- 3.0.0 Migration
-- depends: 

-- Convert warns to infractions
INSERT INTO infractions (guild_id, user_id, moderator_id, created_at, reason)
SELECT guild_id, user_id, mod_id, timestamp, reason FROM warns;

-- Generated by migra
alter table "public"."pardoned_warns" drop constraint "pardoned_warns_guild_id_fkey";

alter table "public"."bug_tickets" drop constraint "bug_tickets_pkey";

alter table "public"."command_plonks" drop constraint "command_plonks_pkey";

alter table "public"."pardoned_warns" drop constraint "pardoned_warns_pkey";

alter table "public"."snipe_settings" drop constraint "snipe_settings_pkey";

alter table "public"."sniped_messages" drop constraint "sniped_messages_pkey";

alter table "public"."staff_roles" drop constraint "staff_roles_pkey";

alter table "public"."toggleable_roles" drop constraint "toggleable_roles_pkey";

alter table "public"."user_restrictions" drop constraint "user_restrictions_pkey";

alter table "public"."userlogs" drop constraint "userlogs_pkey";

alter table "public"."warns" drop constraint "warns_pkey";

drop index if exists "public"."bug_tickets_pkey";

drop index if exists "public"."command_plonks_pkey";

drop index if exists "public"."command_plonks_uniq_idx";

drop index if exists "public"."commands_usage_command_name_idx";

drop index if exists "public"."commands_usage_used_at_idx";

drop index if exists "public"."commands_usage_user_id_idx";

drop index if exists "public"."pardoned_warns_pkey";

drop index if exists "public"."pardoned_warns_uniq_idx";

drop index if exists "public"."snipe_settings_pkey";

drop index if exists "public"."sniped_messages_pkey";

drop index if exists "public"."staff_roles_pkey";

drop index if exists "public"."toggleable_roles_pkey";

drop index if exists "public"."user_restrictions_pkey";

drop index if exists "public"."userlogs_pkey";

drop index if exists "public"."warns_pkey";

drop index if exists "public"."warns_uniq_idx";

drop index if exists "public"."commands_usage_guild_id_idx";

drop table "public"."bug_tickets";

drop table "public"."command_plonks";

drop table "public"."pardoned_warns";

drop table "public"."snipe_settings";

drop table "public"."sniped_messages";

drop table "public"."staff_roles";

drop table "public"."toggleable_roles";

drop table "public"."user_restrictions";

drop table "public"."userlogs";

drop table "public"."warns";

create table "public"."roles" (
    "guild_id" bigint,
    "user_id" bigint,
    "roles" bigint[],
    "punishment_roles" bigint[]
);


alter table "public"."commands_usage" add column "channel_id" bigint;

alter table "public"."commands_usage" alter column "id" drop default;

alter table "public"."commands_usage" alter column "id" add generated by default as identity;

alter table "public"."guild_config" add column "flags" integer;

alter table "public"."guild_config" add column "permissions" jsonb;

alter table "public"."guild_config" add column "toggleroles" bigint[];

alter table "public"."guild_mod_config" drop column "log_channels";

alter table "public"."guild_mod_config" drop column "log_format";

alter table "public"."guild_mod_config" add column "automod_join_threshold_seconds" integer;

alter table "public"."guild_mod_config" add column "automod_join_threshold_users" integer;

alter table "public"."guild_mod_config" add column "raid_mode" boolean default false;

alter table "public"."guild_mod_config" add column "temp_mute_role_id" bigint;

alter table "public"."guild_mod_config" alter column "warn_ban" set data type bigint using "warn_ban"::bigint;

alter table "public"."guild_mod_config" alter column "warn_kick" set data type bigint using "warn_kick"::bigint;

alter table "public"."infractions" add column "expiry" timestamp without time zone;

alter table "public"."nin_updates" alter column "webhook_token" set data type character varying(100) using "webhook_token"::character varying(100);

alter table "public"."timers" alter column "id" drop default;

alter table "public"."timers" alter column "id" add generated by default as identity;

drop sequence if exists "public"."bug_tickets_id_seq";

drop sequence if exists "public"."command_plonks_id_seq";

drop sequence if exists "public"."commands_usage_id_seq";

drop sequence if exists "public"."pardoned_warns_warn_id_seq";

drop sequence if exists "public"."timers_id_seq";

drop sequence if exists "public"."warns_warn_id_seq";

CREATE UNIQUE INDEX roles_guild_id_user_id_key ON public.roles USING btree (guild_id, user_id);

CREATE INDEX commands_usage_guild_id_idx ON public.commands_usage USING btree (user_id, used_at, command_name);

alter table "public"."roles" add constraint "roles_guild_id_user_id_key" UNIQUE using index "roles_guild_id_user_id_key";